baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.beagle.work" # the base hostname & protocol for your site, e.g. http://example.com

lang: nl_BE

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: assets/scss
  style: compressed


# Exclude from processing.
exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - README.md
  - SECURITY.md
  - vendor/bundle/
