#-------------------------------
# General Site Settings

title: Beagle@work
logo: 
author: Beagle@work
description: Beagle@work leidt beagles op als reddingshonden op recreatief niveau. Elke geleider bepaalt zelf welk niveau hij voor ogen heeft met zijn eigen hond.
#email: info@beagle.work
#facebook: https://fb.com/beagle.work
#youtube: https://youtu.be/beagle.work
facebook_url: https://fb.com/beagle.work
youtube_url: https://youtu.be/beagle.work
copyright: Copyright &copy; 2023

menu:
- {name: Over ons, link: '/over-ons'}
- {name: Nieuws, link: '/blog'}
- {name: Teams, link: '/teams'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Speuren met<br />Beagles


#-------------------------------
# About (Section and Page)

# About Section
blurb: >
  ## Wij leren Beagles slachtoffers zoeken
  
  Welkom bij Beagle@Work: de speurvereniging met een neus voor avontuur! Onze enthousiaste gemeenschap van toegewijde leden is gepassioneerd bezig met speurwerk op verschillende locaties, waarbij we de ongeëvenaarde vaardigheden van Beagles benutten om mensen in nood te helpen.
  <br>
  <br>
  Onze trainingen zijn zorgvuldig ontworpen om onze Beagles voor te bereiden op elke uitdaging die ze onderweg kunnen tegenkomen. We beginnen met een reeks korte oefeningen om hun zintuigen te scherpen en hen klaar te maken voor het speurwerk. Het is een opwindende opwarming die hun enthousiasme en concentratie vergroot.
  <br>
  <br>
  Daarna begint het echte avontuur! Meerdere 'slachtoffers' verstoppen zich op strategische plaatsen en onze Beagles worden losgelaten om hun ongelooflijke reukvermogen in te zetten. Met hun neus als kompas gaan ze onverschrokken op zoek naar de vermiste personen. Zodra een Beagle een slachtoffer vindt, blijft hij erbij zitten en blaft hij luidkeels totdat zijn onverschrokken baasje ook ter plaatse is. Dit is ons signaal van succes en we belonen de Beagle voor zijn moedige prestatie.
  <br>
  <br>
  Bij Beagle@Work draait alles om teamwork en vertrouwen. Onze band met deze prachtige dieren groeit met elke trainingssessie. We zijn niet alleen een vereniging, maar ook een hechte familie die elkaar ondersteunt en aanmoedigt. Samen zetten we ons in om de wereld een beetje veiliger te maken door de bijzondere talenten van Beagles te benutten.
  <br>
  <br>
  Als je een avontuurlijke geest hebt en geïnteresseerd bent in speurwerk met Beagles, dan ben je bij ons aan het juiste adres. Beagle@Work is dé plek om je passie voor Beagles en speurwerk te delen met gelijkgestemde leden. We moedigen elkaar aan, delen kennis en genieten van de opwindende wereld van speuren met Beagles!

blurb-btn-link: '/over-ons'
blurb-btn-name: Over Beagle@work

cooperation-title: Samenwerking
cooperations:
# - organization: Hondenschool Kitazz
#   logo: 'kitazz.jpg'
#   explanation: Wij werken samen met deze hondenschool, zodat onze leden indien gewenst ook de nodige ondersteuning kunnen krijgen op het gebied van gehoorzaamheid of andere hondensporten.
#   website: 'https://www.hondenschool-kitazz.be'
#   aspectratio: 1.06

  - organization: Searchdog@work
    logo: 'searchdog.jpg'
    explanation: Voor de honden die net iets meer willen en kunnen bereiken werken we samen met Searchdog@work. Een reddingshonden groep in België die traint volgens de IRO richtlijnen.
    website: 'https://www.searchdog.work'
    aspectratio: 1

# About Page

# Work Process Section
work-process:
  - title : "Slachtofferbinding"
    icon : "assets/images/icons/plan.png"
    content : "Het allerbelangrijkste voor een reddingshond is dat hij graag naar slachtoffers gaat zoeken. Zo krijgen ze telkens hun speeltje of voeding als ze het slachtoffer vinden. Bij beagles is het overgrote deel gemakkelijker te trainen met voeding."
    
  - title : "Neus gebruiken"
    icon : "assets/images/icons/design.png"
    content : "Wanneer ze graag naar de slachtoffers gaan, gaan we ze stilaan uit zicht plaatsen. De honden worden op dat moment gedwongen om hun neus te gaan gebruiken om het slachtoffer te vinden. Als ze dit eenmaal door hebben gaat het snel!"
    
  - title : "Verwijzen"
    icon : "assets/images/icons/print.png"
    content : "Wanneer het slachtoffer werd gevonden moet de hond het slachtoffer verwijzen. Dat kan op allerlei manieren, maar de favoriete manier van bijna alle beagles is het aanblaffen tot de begeleider er is."


# My Team Section
team:
  - title : "Team Tenkie"
    image : "assets/images/team/tenkie.jpg"
    designation : "Mieke & Kris<br />(trainer)"

  - title : "Team Marly"
    image : "assets/images/team/marly-300x300.jpg"
    designation : "Eddy<br/>(trainer)"

  - title : "Team Bailey"
    image : "assets/images/team/bailey.jpg"
    designation : "Danny"

  - title : "Team Juul & Tuur"
    image : "assets/images/team/juul.jpg"
    designation : "Marjolein"

  - title : "Team Obi"
    image : "assets/images/team/obi.png"
    designation : "Sarah"

  - title : "Team Rover"
    image : "assets/images/team/rover.png"
    designation : "Paul"

  #- title : "Team Bikkel"
  #  image : "assets/images/team/bikkel-300x300.jpg"
  #  designation : "Nathalie"

  - title : "Team Bootzy"
    image : "assets/images/team/bootsy-300x300.jpg"
    designation : "Peter"

  - title : "Team Coco"
    image : "assets/images/team/coco.png"
    designation : "Paul"

#  - title : "Team Bailey"
#    image : "assets/images/team/bailey2.png"
#    designation : "Joris"

  - title : "Team Flo"
    image : "assets/images/team/flo_tinne-300x300.jpg"
    designation : "Tinne"

  - title : "Team Max"
    image : "assets/images/team/max.png"
    designation : "Jens"

  - title : "Team Qobe"
    image : "assets/images/team/qobe-300x300.jpg"
    designation : "Diane en Fik"

  #- title : "Team Qyo"
  #  image : "assets/images/team/qyo-300x300.jpg"
  #  designation : "Carlo"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Web Design, color: '#fdb157', value: '90%'}
- {name: Logo Design, color: '#9473e6', value: '60%'}
- {name: After Effects, color: '#bdecf6', value: '80%'}
- {name: Web App, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Junior UX Designer, icon: 'icon-1.png', date: 'Jan 2007 - Feb 2009', organization: 'WEBEX'}
- {name: UX & UI Designer, icon: 'icon-2.png', date: 'Mar 2009 - Aug 2014', organization: 'AUGMEDIX'}
- {name: Senior UI Designer, icon: 'icon-3.png', date: 'Sep 2014 - Present', organization: 'THEMEFISHER'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Marters in UX Design, date: '2006', organization: 'Masassusets Institute of Technology'}
- {name: Honours in Fine Arts, date: '2004', organization: 'Harvard University'}
- {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
- {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}


#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: UI Design,
    icon: ti-palette,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    active: # Add true to select section
  }
- {
    name: UX Design,
    icon: ti-vector,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    active: true # Add true to select section
  }
- {
    name: Interaction Design,
    icon: ti-panel,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "UI/UX Design",
    type : "design"
  }
- {
    title : "BRANDING",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"


#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation : "CEO, Funder"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: steve.fruits@email.com
